[project]
name = "pytest-http-engine"
version = "0.1.0"
description = "utilities for HTTP testing using JSON files"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Alexander Eresov", email = "aeresov@gmail.com" }]
dependencies = [
    "jsonref>=1.1.0",
    "pydantic>=2.11.0",
    "jmespath>=1.0.1",
    "requests>=2.32.4",
    "mergedeep>=1.3.4",
]

[build-system]
requires = ["uv_build>=0.7.21,<0.8.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest-datadir>=1.7.2",
]
