[project]
name = "pytest-http"
version = "0.1.0"
description = "pytest plugin for HTTP testing using JSON files"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Alexander Eresov", email = "aeresov@gmail.com" },
]
dependencies = [
    "pytest>=8.0.0",
    "jsonref>=1.1.0",
    "pydantic>=2.11.0",
    "jmespath>=1.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points.pytest11]
pytest_http = "pytest_http.pytest_plugin"

[tool.hatch.build]
packages = ["pytest_http"]

[tool.ruff]
line-length = 180
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
line-ending = "lf"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["tests", "utils"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
markers = [
    "test: generic marker",
]
norecursedirs = ["examples"]
pytester_example_dir = "tests/examples"

[tool.pyright]
exclude = ["cdk.out/"]
ignore = [".venv/"]
reportMissingImports = "error"
reportMissingTypeStubs = false
reportExplicitAny = false
typeCheckingMode = "off"
pythonPlatform = "Linux"
