[project]
name = "engine"
version = "0.1.0"
description = "utilities for HTTP testing using JSON files"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Alexander Eresov", email = "aeresov@gmail.com" }]
dependencies = [
    "pytest>=8.0.0",
    "jsonref>=1.1.0",
    "pydantic>=2.11.0",
    "jmespath>=1.0.1",
    "requests>=2.32.4",
]

[project.optional-dependencies]
aws = ["requests-auth-aws-sigv4>=0.7.0", "boto3>=1.35.0"]

[dependency-groups]
dev = []

[build-system]
requires = ["uv_build>=0.7.21,<0.8.0"]
build-backend = "uv_build"
