name: Publish to PyPI

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    build-and-publish:
        name: Build and publish to PyPI
        runs-on: ubuntu-latest
        permissions:
            id-token: write # IMPORTANT: mandatory for trusted publishing

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"

            - name: Build all packages
              run: |
                  uv build --all-packages
                  echo "Built packages:"
                  ls -la dist/

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
